---

# https://github.com/Lusitaniae/apache_exporter
# https://github.com/Lusitaniae/apache_exporter/releases/download/v0.5.0/apache_exporter-0.5.0.linux-amd64.tar.gz

  - set_fact:
      apache_exporter_sub_dir: "{{exporter_config.exporter_dir | default('apache_exporter')}}"
      apache_exporter_user: "{{exporter_config.exporter_user | default(prometheus_user)}}"
      apache_exporter_group: "{{exporter_config.exporter_group | default(prometheus_group)}}"

  - name: Prometheus apache Exporter | Download distribution
    get_url:
      url: "https://github.com/Lusitaniae/apache_exporter/releases/download/v{{prometheus_apache_exporter_version}}/apache_exporter-{{prometheus_apache_exporter_version}}.linux-amd64.tar.gz"
      dest: "{{prometheus_exporters_dir}}/apache_exporter-{{prometheus_apache_exporter_version}}.linux-amd64.tar.gz"
    become: yes
    become_user: "{{ apache_exporter_user }}"
    tags:
      - prometheus

  - name: Prometheus apache Exporter | unpack distribution
    unarchive:
      src: "{{prometheus_exporters_dir}}/apache_exporter-{{prometheus_apache_exporter_version}}.linux-amd64.tar.gz"
      dest: "{{prometheus_exporters_dir}}"
      remote_src: yes
    become: yes
    become_user: "{{ apache_exporter_user }}"
    tags:
      - prometheus

  - name: Prometheus apache Exporter | link apache exporter dir
    file: src="{{prometheus_exporters_dir}}/apache_exporter-{{prometheus_apache_exporter_version}}.linux-amd64/" dest="{{prometheus_exporters_dir}}/{{apache_exporter_sub_dir}}" owner="root"  group="{{ apache_exporter_group }}" state=link
    become: yes
    tags:
      - prometheus

  - include_tasks: "tasks_startup.yml exporter_startup_config={{exporter_config}}"
